name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    container: golang:1.21

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Lint code
        run: go fmt ./...

      - name: Run tests
        run: go test ./...

      - name: Debug GitHub Context
        run: "echo 'Ref: ${{ github.ref }}'"

  publish:
    name: Publish to DockerHub
    needs: lint-and-test
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/final-main:${{ github.ref_name }}
          push: true

      - name: Logout from DockerHub
        run: docker logout